# Generated by Django 5.0 on 2023-12-14 14:25

import django.db.models.deletion
import phonenumber_field.modelfields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cName', models.CharField(max_length=255)),
                ('cEmail', models.EmailField(max_length=254)),
                ('cPhone', models.PositiveBigIntegerField()),
                ('cMsg', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Email',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Email', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('uName', models.CharField(max_length=255)),
                ('uEmail', models.EmailField(max_length=254)),
                ('uPass', models.CharField(max_length=255)),
                ('uPhone', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None)),
            ],
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('feedback', models.TextField()),
                ('submitter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sub.user')),
            ],
        ),
    ]
