# Generated by Django 5.0 on 2023-12-20 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sub', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('date_of_birth', models.DateField()),
                ('email', models.EmailField(max_length=254)),
                ('stream', models.CharField(choices=[('science', 'Science'), ('arts', 'Arts'), ('commerce', 'Commerce')], max_length=50)),
                ('subject1', models.CharField(choices=[('Chemistry', 'Chemistry'), ('Physics', 'Physics'), ('Biology', 'Biology'), ('Maths', 'Maths'), ('English', 'English'), ('Computer', 'Computer'), ('P.T', 'P.T'), ('Sanskrit', 'Sanskrit')], max_length=50)),
                ('marks1', models.IntegerField()),
                ('subject2', models.CharField(choices=[('Chemistry', 'Chemistry'), ('Physics', 'Physics'), ('Biology', 'Biology'), ('Maths', 'Maths'), ('English', 'English'), ('Computer', 'Computer'), ('P.T', 'P.T'), ('Sanskrit', 'Sanskrit')], max_length=50)),
                ('marks2', models.IntegerField()),
                ('subject3', models.CharField(choices=[('Chemistry', 'Chemistry'), ('Physics', 'Physics'), ('Biology', 'Biology'), ('Maths', 'Maths'), ('English', 'English'), ('Computer', 'Computer'), ('P.T', 'P.T'), ('Sanskrit', 'Sanskrit')], max_length=50)),
                ('marks3', models.IntegerField()),
                ('skills', models.TextField(blank=True)),
                ('interested_subjects', models.TextField(blank=True)),
            ],
        ),
    ]
