# Generated by Django 5.0 on 2023-12-20 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sub', '0003_alter_student_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='seat_no',
            field=models.CharField(default=0, max_length=20),
            preserve_default=False,
        ),
    ]
