# Generated by Django 5.0 on 2024-02-29 13:36

import django.db.models.deletion
import phonenumber_field.modelfields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='College',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.TextField(default='null')),
                ('address', models.TextField(blank=True, max_length=255)),
                ('placement', models.CharField(blank=True, max_length=255)),
                ('hostel', models.CharField(blank=True, max_length=255)),
                ('transport', models.CharField(blank=True, max_length=255)),
                ('link', models.TextField(blank=True, max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cName', models.CharField(max_length=255)),
                ('cEmail', models.EmailField(max_length=254)),
                ('cPhone', models.PositiveBigIntegerField()),
                ('cMsg', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='MCQ',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('subject', models.CharField(default='timepass', max_length=255)),
                ('question', models.TextField(max_length=255)),
                ('optionA', models.TextField(max_length=255)),
                ('optionB', models.TextField(max_length=255)),
                ('optionC', models.TextField(max_length=255)),
                ('optionD', models.TextField(max_length=255)),
                ('correct', models.CharField(max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('date_of_birth', models.DateField(null=True)),
                ('seat_no', models.CharField(max_length=20)),
                ('stream', models.CharField(max_length=50)),
                ('subject1', models.CharField(choices=[('Chemistry', 'Chemistry'), ('Physics', 'Physics'), ('Biology', 'Biology'), ('Maths', 'Maths'), ('English', 'English'), ('Computer', 'Computer'), ('P.T', 'P.T'), ('Sanskrit', 'Sanskrit'), ('Accounts', 'Accounts'), ('Statistics', 'Statistics'), ('Economics', 'Economics'), ('Business Administration', 'Business Administration'), ('Gujarati', 'Gujarati'), ('Political Science', 'Political Science'), ('History', 'History'), ('Geography', 'Geography'), ('Accounting', 'Accounting'), ('Sociology', 'Sociology')], max_length=50)),
                ('marks1', models.IntegerField(default=0)),
                ('subject2', models.CharField(choices=[('Chemistry', 'Chemistry'), ('Physics', 'Physics'), ('Biology', 'Biology'), ('Maths', 'Maths'), ('English', 'English'), ('Computer', 'Computer'), ('P.T', 'P.T'), ('Sanskrit', 'Sanskrit'), ('Accounts', 'Accounts'), ('Statistics', 'Statistics'), ('Economics', 'Economics'), ('Business Administration', 'Business Administration'), ('Gujarati', 'Gujarati'), ('Political Science', 'Political Science'), ('History', 'History'), ('Geography', 'Geography'), ('Accounting', 'Accounting'), ('Sociology', 'Sociology')], max_length=50)),
                ('marks2', models.IntegerField(default=0)),
                ('subject3', models.CharField(choices=[('Chemistry', 'Chemistry'), ('Physics', 'Physics'), ('Biology', 'Biology'), ('Maths', 'Maths'), ('English', 'English'), ('Computer', 'Computer'), ('P.T', 'P.T'), ('Sanskrit', 'Sanskrit'), ('Accounts', 'Accounts'), ('Statistics', 'Statistics'), ('Economics', 'Economics'), ('Business Administration', 'Business Administration'), ('Gujarati', 'Gujarati'), ('Political Science', 'Political Science'), ('History', 'History'), ('Geography', 'Geography'), ('Accounting', 'Accounting'), ('Sociology', 'Sociology')], max_length=50)),
                ('marks3', models.IntegerField(default=0)),
                ('skills', models.TextField(max_length=250)),
                ('interested_subjects', models.TextField(max_length=250)),
                ('result', models.TextField(max_length=250)),
                ('score', models.IntegerField(default=-1)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('uName', models.CharField(max_length=255, unique=True)),
                ('uEmail', models.EmailField(max_length=254)),
                ('uPass', models.CharField(max_length=255)),
                ('uPhone', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None)),
            ],
        ),
        migrations.CreateModel(
            name='Stream',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.TextField(blank=True, default='null')),
                ('desc', models.TextField(blank=True, default='null')),
                ('fees', models.CharField(blank=True, default=-1, max_length=255)),
                ('description', models.TextField(blank=True, default='Null', max_length=255)),
                ('college_name', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='sub.college')),
            ],
        ),
        migrations.AddField(
            model_name='college',
            name='courses',
            field=models.ManyToManyField(blank=True, to='sub.stream'),
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('feedback', models.TextField()),
                ('submitter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sub.user')),
            ],
        ),
    ]
