# Generated by Django 5.0 on 2024-01-22 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sub', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='college',
            name='streams',
        ),
        migrations.AddField(
            model_name='college',
            name='Stuff',
            field=models.ManyToManyField(to='sub.stream'),
        ),
    ]
