# Generated by Django 5.0 on 2024-02-29 13:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sub', '0002_user_student'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='Student',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='sub.student'),
        ),
    ]
