# Generated by Django 5.0 on 2024-01-22 14:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sub', '0002_remove_college_streams_college_stuff'),
    ]

    operations = [
        migrations.RenameField(
            model_name='college',
            old_name='Stuff',
            new_name='courses',
        ),
    ]
