# Generated by Django 5.0 on 2024-01-22 15:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sub', '0003_rename_stuff_college_courses'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stream',
            old_name='desctiption',
            new_name='description',
        ),
    ]
