# Generated by Django 5.0 on 2024-01-22 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sub', '0004_rename_desctiption_stream_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='college',
            name='courses',
            field=models.ManyToManyField(blank=True, to='sub.stream'),
        ),
    ]
