# Generated by Django 5.0 on 2023-12-24 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sub', '0004_student_seat_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='date_of_birth',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AlterField(
            model_name='student',
            name='first_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='student',
            name='last_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='student',
            name='marks1',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='marks2',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='marks3',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='seat_no',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='student',
            name='stream',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='student',
            name='subject1',
            field=models.CharField(blank=True, choices=[('Chemistry', 'Chemistry'), ('Physics', 'Physics'), ('Biology', 'Biology'), ('Maths', 'Maths'), ('English', 'English'), ('Computer', 'Computer'), ('P.T', 'P.T'), ('Sanskrit', 'Sanskrit')], max_length=50),
        ),
        migrations.AlterField(
            model_name='student',
            name='subject2',
            field=models.CharField(blank=True, choices=[('Chemistry', 'Chemistry'), ('Physics', 'Physics'), ('Biology', 'Biology'), ('Maths', 'Maths'), ('English', 'English'), ('Computer', 'Computer'), ('P.T', 'P.T'), ('Sanskrit', 'Sanskrit')], max_length=50),
        ),
        migrations.AlterField(
            model_name='student',
            name='subject3',
            field=models.CharField(blank=True, choices=[('Chemistry', 'Chemistry'), ('Physics', 'Physics'), ('Biology', 'Biology'), ('Maths', 'Maths'), ('English', 'English'), ('Computer', 'Computer'), ('P.T', 'P.T'), ('Sanskrit', 'Sanskrit')], max_length=50),
        ),
    ]
