# Generated by Django 5.0 on 2024-03-02 08:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sub', '0004_student_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stream',
            name='desc',
        ),
        migrations.AlterField(
            model_name='user',
            name='Student',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='sub.student'),
        ),
    ]
