# Generated by Django 5.0 on 2023-12-27 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sub', '0005_alter_student_date_of_birth_alter_student_email_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MCQQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.CharField(max_length=255)),
                ('options', models.CharField(choices=[('Option A', 'Option A'), ('Option B', 'Option B'), ('Option C', 'Option C'), ('Option D', 'Option D')], default='Option A', max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='student',
            name='date_of_birth',
            field=models.DateField(default=0),
        ),
        migrations.AlterField(
            model_name='student',
            name='email',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='student',
            name='first_name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='student',
            name='interested_subjects',
            field=models.TextField(max_length=250),
        ),
        migrations.AlterField(
            model_name='student',
            name='last_name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='student',
            name='marks1',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='student',
            name='marks2',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='student',
            name='marks3',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='student',
            name='seat_no',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='student',
            name='skills',
            field=models.TextField(max_length=250),
        ),
        migrations.AlterField(
            model_name='student',
            name='stream',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='student',
            name='subject1',
            field=models.CharField(choices=[('Chemistry', 'Chemistry'), ('Physics', 'Physics'), ('Biology', 'Biology'), ('Maths', 'Maths'), ('English', 'English'), ('Computer', 'Computer'), ('P.T', 'P.T'), ('Sanskrit', 'Sanskrit'), ('Accounts', 'Accounts'), ('Statistics', 'Statistics'), ('Economics', 'Economics'), ('Business Administration', 'Business Administration'), ('Gujarati', 'Gujarati'), ('Yoga & Health', 'Yoga & Health'), ('Political Science', 'Political Science'), ('History', 'History'), ('Geography', 'Geography'), ('Accounting', 'Accounting'), ('Sociology', 'Sociology')], max_length=50),
        ),
        migrations.AlterField(
            model_name='student',
            name='subject2',
            field=models.CharField(choices=[('Chemistry', 'Chemistry'), ('Physics', 'Physics'), ('Biology', 'Biology'), ('Maths', 'Maths'), ('English', 'English'), ('Computer', 'Computer'), ('P.T', 'P.T'), ('Sanskrit', 'Sanskrit'), ('Accounts', 'Accounts'), ('Statistics', 'Statistics'), ('Economics', 'Economics'), ('Business Administration', 'Business Administration'), ('Gujarati', 'Gujarati'), ('Yoga & Health', 'Yoga & Health'), ('Political Science', 'Political Science'), ('History', 'History'), ('Geography', 'Geography'), ('Accounting', 'Accounting'), ('Sociology', 'Sociology')], max_length=50),
        ),
        migrations.AlterField(
            model_name='student',
            name='subject3',
            field=models.CharField(choices=[('Chemistry', 'Chemistry'), ('Physics', 'Physics'), ('Biology', 'Biology'), ('Maths', 'Maths'), ('English', 'English'), ('Computer', 'Computer'), ('P.T', 'P.T'), ('Sanskrit', 'Sanskrit'), ('Accounts', 'Accounts'), ('Statistics', 'Statistics'), ('Economics', 'Economics'), ('Business Administration', 'Business Administration'), ('Gujarati', 'Gujarati'), ('Yoga & Health', 'Yoga & Health'), ('Political Science', 'Political Science'), ('History', 'History'), ('Geography', 'Geography'), ('Accounting', 'Accounting'), ('Sociology', 'Sociology')], max_length=50),
        ),
    ]
