# Generated by Django 5.0 on 2024-01-22 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sub', '0005_alter_college_courses'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stream',
            name='description',
            field=models.TextField(blank=True, default='Null', max_length=255),
        ),
        migrations.AlterField(
            model_name='stream',
            name='fees',
            field=models.CharField(blank=True, default=-1, max_length=255),
        ),
    ]
