# Generated by Django 5.0 on 2023-12-27 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sub', '0006_mcqquestion_alter_student_date_of_birth_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='date_of_birth',
            field=models.DateField(null=True),
        ),
    ]
