# Generated by Django 5.0 on 2024-02-08 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sub', '0006_alter_stream_description_alter_stream_fees'),
    ]

    operations = [
        migrations.AddField(
            model_name='stream',
            name='desc',
            field=models.TextField(blank=True, default='null'),
        ),
    ]
