# Generated by Django 5.0 on 2024-02-09 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sub', '0007_stream_desc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='uName',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
