# Generated by Django 5.0 on 2023-12-27 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sub', '0007_alter_student_date_of_birth'),
    ]

    operations = [
        migrations.CreateModel(
            name='MCQModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
    ]
