# Generated by Django 5.0 on 2023-12-27 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sub', '0008_mcqmodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='MCQ',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('question', models.TextField(max_length=255)),
                ('optionA', models.TextField(max_length=255)),
                ('optionB', models.TextField(max_length=255)),
                ('optionC', models.TextField(max_length=255)),
                ('optionD', models.TextField(max_length=255)),
                ('correct', models.CharField(max_length=2)),
            ],
        ),
        migrations.DeleteModel(
            name='MCQModel',
        ),
        migrations.DeleteModel(
            name='MCQQuestion',
        ),
    ]
