# Generated by Django 5.0 on 2023-12-29 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sub', '0009_mcq_delete_mcqmodel_delete_mcqquestion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='subject1',
            field=models.CharField(choices=[('Chemistry', 'Chemistry'), ('Physics', 'Physics'), ('Biology', 'Biology'), ('Maths', 'Maths'), ('English', 'English'), ('Computer', 'Computer'), ('P.T', 'P.T'), ('Sanskrit', 'Sanskrit'), ('Accounts', 'Accounts'), ('Statistics', 'Statistics'), ('Economics', 'Economics'), ('Business Administration', 'Business Administration'), ('Gujarati', 'Gujarati'), ('Political Science', 'Political Science'), ('History', 'History'), ('Geography', 'Geography'), ('Accounting', 'Accounting'), ('Sociology', 'Sociology')], max_length=50),
        ),
        migrations.AlterField(
            model_name='student',
            name='subject2',
            field=models.CharField(choices=[('Chemistry', 'Chemistry'), ('Physics', 'Physics'), ('Biology', 'Biology'), ('Maths', 'Maths'), ('English', 'English'), ('Computer', 'Computer'), ('P.T', 'P.T'), ('Sanskrit', 'Sanskrit'), ('Accounts', 'Accounts'), ('Statistics', 'Statistics'), ('Economics', 'Economics'), ('Business Administration', 'Business Administration'), ('Gujarati', 'Gujarati'), ('Political Science', 'Political Science'), ('History', 'History'), ('Geography', 'Geography'), ('Accounting', 'Accounting'), ('Sociology', 'Sociology')], max_length=50),
        ),
        migrations.AlterField(
            model_name='student',
            name='subject3',
            field=models.CharField(choices=[('Chemistry', 'Chemistry'), ('Physics', 'Physics'), ('Biology', 'Biology'), ('Maths', 'Maths'), ('English', 'English'), ('Computer', 'Computer'), ('P.T', 'P.T'), ('Sanskrit', 'Sanskrit'), ('Accounts', 'Accounts'), ('Statistics', 'Statistics'), ('Economics', 'Economics'), ('Business Administration', 'Business Administration'), ('Gujarati', 'Gujarati'), ('Political Science', 'Political Science'), ('History', 'History'), ('Geography', 'Geography'), ('Accounting', 'Accounting'), ('Sociology', 'Sociology')], max_length=50),
        ),
    ]
