# Generated by Django 5.0 on 2023-12-30 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sub', '0010_alter_student_subject1_alter_student_subject2_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mcq',
            name='subject',
            field=models.CharField(default='timepass', max_length=255),
        ),
    ]
